import type { AdBanner, Publication } from "@/lib/types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  DEMO DATA — development only.
 *
 *  Every read in lib/queries.ts hits Supabase first and only falls back to this
 *  file when the database is unreachable or genuinely empty. Publishing a
 *  single real issue replaces the whole set, so nothing here needs deleting
 *  before launch.
 *
 *  The covers are generated by scripts/generate-covers.mjs and the PDF is the
 *  same short sample for every edition — enough to exercise the reader without
 *  shipping 18 large binaries.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** Matches public/sample.pdf, built by scripts/generate-demo-pdf.mjs. */
const DEMO_PDF_PAGES = 8;

const START_ISSUE = 204;
/** Sunday 6 September 2026 — the most recent demo edition. */
const START_DATE = Date.UTC(2026, 8, 6);
const WEEKS = 18;

/** What a given week's edition leads with. Cycled, so no two neighbours match. */
const FOCUS = [
  {
    lead: "Autumn hiring across the Greater Toronto Area",
    body: "Vacancies from local employers, trade and warehouse roles, plus a full run of property listings and this week's service directory.",
  },
  {
    lead: "Property and rentals week",
    body: "An expanded property section — homes, rooms and commercial units to rent or buy — alongside the regular business, services and community pages.",
  },
  {
    lead: "Home and trade services",
    body: "Plumbers, electricians, movers, cleaners and repair specialists, with the week's business promotions and classified listings.",
  },
  {
    lead: "Weekend offers and promotions",
    body: "Seasonal deals from local shops and restaurants, plus jobs, property, professional services and community notices.",
  },
  {
    lead: "New businesses in the neighbourhood",
    body: "Openings and introductions from local firms, together with the standing property, jobs and services sections.",
  },
  {
    lead: "Community notices and classes",
    body: "Events, classes and announcements from local organisations, running alongside the week's full advertising sections.",
  },
];

function isoDate(weeksAgo: number) {
  return new Date(START_DATE - weeksAgo * 7 * 86400000).toISOString().slice(0, 10);
}

export const DEMO_PUBLICATIONS: Publication[] = Array.from({ length: WEEKS }, (_, i) => {
  const issue = START_ISSUE - i;
  const date = isoDate(i);
  const focus = FOCUS[i % FOCUS.length];

  return {
    id: `demo-issue-${issue}`,
    created_at: `${date}T06:00:00Z`,
    title: `Issue ${issue}`,
    slug: `issue-${issue}`,
    description: `${focus.lead}. ${focus.body}`,
    edition: "weekly",
    edition_date: date,
    pdf_url: "/sample.pdf",
    pdf_key: `editions/vaaram-issue-${issue}.pdf`,
    // Every demo edition opens the same generated PDF, so the page count and
    // file size describe that file honestly rather than inventing a number a
    // reader would disprove the moment they opened it.
    file_size_bytes: 39922,
    total_pages: DEMO_PDF_PAGES,
    cover_url: `/covers/issue-${issue}.svg`,
    is_published: true,
    view_count: 0,
    download_count: 0,
  } satisfies Publication;
});

/**
 * Placeholder bookings so the rails, strips and footer grid can be laid out
 * and checked at every screen size while the banners table is still empty.
 *
 * Unlike the demo editions above, these are **development only** — getBanners
 * refuses to fall back to them in a production build. A placeholder edition is
 * a harmless stand-in, but a placeholder advertiser is a commercial claim about
 * a business that never booked anything, with impression and click counts
 * behind it that would be invented.
 *
 * The artwork is generated by scripts/generate-demo-ads.mjs at the exact two
 * proportions the site sells, so what these prove about the layout holds for
 * real artwork too. Every name is fictitious.
 */
const DEMO_ADVERTISERS = [
  "Sri Balaji Motors", "Kandan Grocery", "Maple Dental Care", "Thamarai Catering",
  "Vannan Movers", "Aruna Tailors", "Nithya Travels", "Ravi Plumbing",
  "Selvi Jewellers", "Anbu Driving School", "Ilango Law Office", "Priya Beauty Salon",
  "Murugan Sweets", "Kumar Auto Glass", "Vasanth Electrical", "Nila Daycare",
  "Thendral Printing", "Bala Accounting", "Sakthi Hardware", "Mala Textiles",
  "Arasu Real Estate", "Devi Pharmacy", "Kavi Photography", "Suriya Roofing",
];

/**
 * Stable ids that are genuinely valid UUIDs, so the tracking path is exercised
 * end to end. Every character has to be hexadecimal — the counter endpoint
 * validates the shape and drops anything that is not, so a memorable-looking
 * prefix with a letter outside a–f in it would silently count nothing.
 */
function demoId(n: number) {
  const hex = n.toString(16).padStart(12, "0");
  return `0ad0ad00-0000-4000-8000-${hex}`;
}

function demoBanner(
  n: number,
  placement: AdBanner["placement"],
  artwork: string,
  sortOrder: number
): AdBanner {
  return {
    id: demoId(n),
    created_at: new Date(START_DATE).toISOString(),
    client_name: DEMO_ADVERTISERS[n % DEMO_ADVERTISERS.length],
    target_url: null,
    image_url: artwork,
    image_key: null,
    image_url_tablet: null,
    image_key_tablet: null,
    image_url_mobile: null,
    image_key_mobile: null,
    placement,
    edition: null,
    sort_order: sortOrder,
    is_active: true,
    starts_at: null,
    expires_at: null,
    impressions: 0,
    clicks: 0,
  };
}

const card = (i: number) => `/ads/card-${String(i).padStart(2, "0")}.svg`;
const strip = (i: number) => `/ads/strip-${String(i).padStart(2, "0")}.svg`;

export const DEMO_BANNERS: AdBanner[] = [
  // The main rail — deliberately long, to prove a rail of this depth behaves
  // at every width.
  ...Array.from({ length: 14 }, (_, i) =>
    demoBanner(i, "site_rail", card(i + 1), (i + 1) * 10)
  ),
  // The reader's own rail, which tops itself up from the one above.
  ...Array.from({ length: 5 }, (_, i) =>
    demoBanner(20 + i, "reader_rail", card(i + 15), (i + 1) * 10)
  ),
  // One strip in each wide slot.
  ...(
    [
      "home_hero", "home_mid", "home_feature", "home_closing",
      "listing_top", "listing_inline", "reader_top", "reader_below",
    ] as const
  ).map((placement, i) => demoBanner(40 + i, placement, strip(i + 1), 10)),
  // The footer grid, on every page.
  ...Array.from({ length: 8 }, (_, i) =>
    demoBanner(60 + i, "footer", card(i + 17 > 24 ? i + 1 : i + 17), (i + 1) * 10)
  ),
];
