import type { AdBanner, Publication } from "@/lib/types";

/**
 * ─────────────────────────────────────────────────────────────────────────────
 *  DEMO DATA — development only.
 *
 *  Every read in lib/queries.ts hits Supabase first and only falls back to this
 *  file when the database is unreachable or genuinely empty. Publishing a
 *  single real issue replaces the whole set, so nothing here needs deleting
 *  before launch.
 *
 *  The covers are generated by scripts/generate-covers.mjs and the PDF is the
 *  same short sample for every edition — enough to exercise the reader without
 *  shipping 18 large binaries.
 * ─────────────────────────────────────────────────────────────────────────────
 */

/** Matches public/sample.pdf, built by scripts/generate-demo-pdf.mjs. */
const DEMO_PDF_PAGES = 8;

const START_ISSUE = 204;
/** Sunday 6 September 2026 — the most recent demo edition. */
const START_DATE = Date.UTC(2026, 8, 6);
const WEEKS = 18;

/** What a given week's edition leads with. Cycled, so no two neighbours match. */
const FOCUS = [
  {
    lead: "Autumn hiring across the Greater Toronto Area",
    body: "Vacancies from local employers, trade and warehouse roles, plus a full run of property listings and this week's service directory.",
  },
  {
    lead: "Property and rentals week",
    body: "An expanded property section — homes, rooms and commercial units to rent or buy — alongside the regular business, services and community pages.",
  },
  {
    lead: "Home and trade services",
    body: "Plumbers, electricians, movers, cleaners and repair specialists, with the week's business promotions and classified listings.",
  },
  {
    lead: "Weekend offers and promotions",
    body: "Seasonal deals from local shops and restaurants, plus jobs, property, professional services and community notices.",
  },
  {
    lead: "New businesses in the neighbourhood",
    body: "Openings and introductions from local firms, together with the standing property, jobs and services sections.",
  },
  {
    lead: "Community notices and classes",
    body: "Events, classes and announcements from local organisations, running alongside the week's full advertising sections.",
  },
];

function isoDate(weeksAgo: number) {
  return new Date(START_DATE - weeksAgo * 7 * 86400000).toISOString().slice(0, 10);
}

export const DEMO_PUBLICATIONS: Publication[] = Array.from({ length: WEEKS }, (_, i) => {
  const issue = START_ISSUE - i;
  const date = isoDate(i);
  const focus = FOCUS[i % FOCUS.length];

  return {
    id: `demo-issue-${issue}`,
    created_at: `${date}T06:00:00Z`,
    title: `Issue ${issue}`,
    slug: `issue-${issue}`,
    description: `${focus.lead}. ${focus.body}`,
    edition: "weekly",
    edition_date: date,
    pdf_url: "/sample.pdf",
    pdf_key: `editions/vaaram-issue-${issue}.pdf`,
    // Every demo edition opens the same generated PDF, so the page count and
    // file size describe that file honestly rather than inventing a number a
    // reader would disprove the moment they opened it.
    file_size_bytes: 39922,
    total_pages: DEMO_PDF_PAGES,
    cover_url: `/covers/issue-${issue}.svg`,
    is_published: true,
    view_count: 0,
    download_count: 0,
  } satisfies Publication;
});

/**
 * Placeholder banners so the advertisement slots can be seen and reviewed
 * during development. These are marked `is_demo` by the AdSlot that renders
 * them and are never shown once real banners exist in the database.
 */
export const DEMO_BANNERS: AdBanner[] = [];
